name: CodeQL

on:
  push:
  pull_request:
  schedule:
    - cron: '0 7 * * 5'

jobs:
  Analyse:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3.5.3
    - uses: github/codeql-action/init@v2
      with:
        languages: javascript
        config-file: ./.github/codeql-analysis.yml
      
    - uses: github/codeql-action/analyze@v2
